Modification de mot de passe uniquement par l'utilisateur et modifica…
milleetunmots/app pull request #102
Opened 2021-06-19 14:41 UTC by aristidebamenou

Modifications

2021-06-21 07:29 UTC, levraipixel requested changes

2021-06-21 07:29 UTC, levraipixel commented on app/admin/admin_user.rb
> +      if current_admin_user == admin_user_in_params || !params[:id]
On ne veut pas qu'un admin puisse reset le mot de passe d'un autre utilisateur, c'est ça ?

2021-06-21 07:29 UTC, levraipixel commented on app/admin/admin_user.rb
> +      if current_admin_user.admin?
Le problème ici c'est qu'un admin malin et mal intentionné peut ajouter un champ de formulaire `user_role` et ça fonctionnera car l'attribut est dans `permit_params`

2021-06-21 07:29 UTC, levraipixel commented on app/models/ability.rb
> +    can :update, AdminUser
Ici on veut qu'il ne puisse update que lui-même, non ?

2021-06-21 07:35 UTC, aristidebamenou commented on app/admin/admin_user.rb
> +      if current_admin_user == admin_user_in_params || !params[:id]
oui c'est ça

2021-06-21 07:36 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
oui lui même, avec les if dans le formulaire, il ne pourra pas modifier celui des autres. Sauf peut etre grace à une injection

2021-06-21 08:54 UTC, aristidebamenou commented on app/admin/admin_user.rb
> +      if current_admin_user.admin?
on peut mettre le permit_params sous un if?

2021-06-21 08:58 UTC, levraipixel commented on app/models/ability.rb
> +    can :update, AdminUser
en modifiant l'URL il peut accéder au formulaire d'un autre admin, non ?

2021-06-21 08:59 UTC, levraipixel commented on app/admin/admin_user.rb
> +      if current_admin_user.admin?
non, il faut ruser autrement

2021-06-21 09:00 UTC, levraipixel commented on app/admin/admin_user.rb
> +      if current_admin_user.admin?
oh en fait si

2021-06-21 09:01 UTC, levraipixel commented on app/admin/admin_user.rb
> +      if current_admin_user.admin?
```
permit_params do
   params = [:toto, :tutu]
   params.push :titi if current_user.admin?
   params
end
```

2021-06-21 09:01 UTC, levraipixel commented on app/admin/admin_user.rb
> +      if current_admin_user == admin_user_in_params || !params[:id]
ok

2021-06-21 09:14 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
C'est possible de modifer l'url d'un post?

2021-06-21 09:28 UTC, levraipixel commented on app/models/ability.rb
> +    can :update, AdminUser
pas besoin :
1. tu accèdes au form de ton propre compte
2. tu changes l'URL
3. tu te retrouves sur le form d'un autre compte

2021-06-21 09:30 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
Oui on peut acceder au form d'un autre en modifiant l'url. Mais on aura accès qu'à son nom et son email

2021-06-21 09:30 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
`form do |f|
    if current_admin_user == admin_user_in_params || !params[:id]
      f.inputs do
          f.input :name
          f.input :email
          if current_admin_user.admin?
            f.input :user_role,
              collection: admin_user_role_select_collection,
              input_html: {data: {select2: {}}}
            end
          f.input :password
          f.input :password_confirmation, required: true
        end
      f.actions
    end
  end`

2021-06-21 09:31 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
et avec ça, je peux cacher tous les champs

2021-06-21 09:32 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
J'ai ajouté 
` if current_admin_user == admin_user_in_params || !params[:id]`
au debut du form

2021-06-21 09:35 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
ou
je rajoute juste ça
`can :update, AdminUser, id: user.id`

2021-06-21 09:36 UTC, aristidebamenou commented on app/models/ability.rb
> +    can :update, AdminUser
a Ability. Comme ca, il ne peux pas acceder au form d'un autre

2021-06-21 10:05 UTC, levraipixel requested changes

2021-06-21 10:05 UTC, levraipixel commented on app/admin/admin_user.rb
> +  permit_params
?

2021-06-21 10:05 UTC, levraipixel commented on app/admin/admin_user.rb
> +    params = [:name, :email, :password, :password_confirmation]
Je rajouterai ici `password` et `password_confirmation` uniquement si `current_admin_user == resource`

2021-06-21 10:05 UTC, levraipixel commented on app/models/ability.rb
> +    can :update, AdminUser, id: user.id
Yes parfait

2021-06-21 10:30 UTC, aristidebamenou commented on app/admin/admin_user.rb
> +    params = [:name, :email, :password, :password_confirmation]
et pour créer? il n'y aurait pas de resource

2021-06-21 12:42 UTC, aristidebamenou commented on app/admin/admin_user.rb
> +    params = [:name, :email, :password, :password_confirmation]
`if current_admin_user == params[:id]
      parameters.push :password
      parameters.push :password_confirmation
    end`

2021-06-21 12:43 UTC, aristidebamenou commented on app/admin/admin_user.rb
> +    params = [:name, :email, :password, :password_confirmation]
au lieu de resource, j'ai mis params[id]

2021-06-21 14:53 UTC, levraipixel requested changes

2021-06-21 14:53 UTC, levraipixel commented on app/admin/admin_user.rb
> +    if current_admin_user == params[:id]
Mais ça c'est impossible, `current_admin_user` c'est un objet de type `AdminUser` et `params[:id]` c'est un String

2021-06-21 14:53 UTC, levraipixel commented on app/admin/admin_user.rb
> +      if current_admin_user == admin_user_in_params || !params[:id]
Ici ceci sera mieux : `if !params[:id] || current_admin_user == admin_user_in_params`

2021-06-21 15:33 UTC, aristidebamenou commented on app/admin/admin_user.rb
> +    if current_admin_user == params[:id]
Oops je voulais mettre 
`if !params[:id] || current_admin_user == admin_user_in_params`

2021-06-22 13:48 UTC, levraipixel approved these changes

2021-06-22 14:19 UTC, merged