Books quantity by slices
milleetunmots/app pull request #115
Opened 2021-07-12 14:35 UTC by aristidebamenou

2021-07-12 15:12 UTC, levraipixel requested changes

2021-07-12 15:12 UTC, levraipixel commented on db/migrate/20210712125915_change_call1_books_quantity_type_for_child_support.rb
> +    change_column :child_supports, :call1_books_quantity, :string
Tu ne migres pas les données existantes ?

2021-07-12 15:26 UTC, aristidebamenou commented on db/migrate/20210712125915_change_call1_books_quantity_type_for_child_support.rb
> +    change_column :child_supports, :call1_books_quantity, :string
je parcours la base de données pour mettre à jour les anciennes fiches de suivi?

2021-07-12 16:01 UTC, levraipixel commented on db/migrate/20210712125915_change_call1_books_quantity_type_for_child_support.rb
> +    change_column :child_supports, :call1_books_quantity, :string
Je pense que ce serait bien, oui, sinon on va perdre toute la donnée actuelle

2021-07-13 08:27 UTC, aristidebamenou commented on db/migrate/20210712125915_change_call1_books_quantity_type_for_child_support.rb
> +    change_column :child_supports, :call1_books_quantity, :string
Du coup, je le fais sous rails c?

2021-07-13 08:27 UTC, aristidebamenou commented on db/migrate/20210712125915_change_call1_books_quantity_type_for_child_support.rb
> +    change_column :child_supports, :call1_books_quantity, :string
`class ChangeCall1BooksQuantityTypeForChildSupport < ActiveRecord::Migration[6.0]
  def up
    change_column :child_supports, :call1_books_quantity, :string, using: 'call1_books_quantity::integer'
  end

  def down
    change_column :child_supports, :call1_books_quantity, :integer
  end
end`

2021-07-14 10:31 UTC, levraipixel approved these changes

2021-07-15 16:48 UTC, merged