Envoi de module
milleetunmots/app pull request #126
Opened 2021-08-04 13:56 UTC by aristidebamenou

2021-08-19 08:01 UTC, karquelf requested changes
Il faut rebase t'a PR sur develop (on peut faire ca ensemble tout a l'heure si besoin) car les modifes sur les fichiers app/services/program_message_service.rb et app/admin/message.rb vont écraser les versions à jour de develop là

2021-08-19 08:10 UTC, karquelf requested changes

2021-08-19 08:10 UTC, karquelf commented on app/services/program_module_service.rb
> +    get_all_phone_numbers
il va te manquer ces méthodes pour que le service fonctionne, mais cf mon 1er commentaire, il faudrait surement se baser sur la version à jour de program_sms_service.rb et potentiellement faire une classe de base avec les methodes en communes et faire hériter program_sms_service et program_module_service de cette classe de base

2021-08-20 13:18 UTC, levraipixel commented on app/helpers/program_messages_helper.rb
> +  def get_recipients
Il vaudrait mieux accepter un argument ici et ne pas utiliser `params`

2021-08-20 13:18 UTC, levraipixel commented on app/helpers/program_messages_helper.rb
> +  def get_redirection_targets
Idem ici

2021-08-20 13:20 UTC, levraipixel commented on app/admin/message.rb
> +      results: get_redirection_targets
Tu peux passer `params[:term]` en argument ici plutôt

2021-08-31 18:34 UTC, merged