Mise en prod du 9 Novembre
milleetunmots/app pull request #185
Opened 2021-11-08 11:31 UTC by aristidebamenou

- Bug lors de la modification d'un enfant
- Bug attribution des tags (retour au code initial de dsl de tag)
- Créer et faire apparaître les tranches d'âges dans les exports CSV 
- Bloquer l'inscription lorsque le même numéro est rentré deux fois
- Ajouter un champs avec la liste des PMI dans le formulaire PMI
- Changer la case "Statut de l'appel"

2021-11-08 13:14 UTC, levraipixel commented on app/models/child.rb
> +  def age_range
Ça ça va plutôt dans un décorateur

2021-11-08 13:15 UTC, levraipixel commented on app/models/child_support.rb
> +    validates "call#{call_idx}_status",
Comment tu vas faire pour les statuts existants ? Les fiches deviennent invalides sans qu'on s'en rende compte ?

2021-11-08 13:16 UTC, levraipixel commented on app/views/children/new.html.erb
> +            <% if @registration_source_collection == :pro %>
C'est bizarre, ça. C'est pas un tableau, `@registration_source_collection` ?

2021-11-08 13:17 UTC, levraipixel requested changes
cf commentaires

2021-11-08 13:20 UTC, aristidebamenou commented on app/models/child_support.rb
> +    validates "call#{call_idx}_status",
Non, ce n'est valable que pour les fiches qu'on créera. J'ai mis un on: :create

2021-11-08 13:29 UTC, aristidebamenou commented on app/views/children/new.html.erb
> +            <% if @registration_source_collection == :pro %>
Dans children_controller, on a before_action :build_variables, only: %i[new create]. Et voici le code de  build_variables
`def build_variables
    @title = I18n.t("inscription_title.form#{current_registration_origin}")
    @banner = I18n.t("inscription_banner.form#{current_registration_origin}")
    case current_registration_origin
    when 3
      @terms_accepted_at_label = I18n.t('inscription_terms_accepted_at_label.pro')
      @registration_source_label = I18n.t('inscription_registration_source_label.pro')
      @registration_source_collection = :pro
      @registration_pmi_detail = I18n.t('inscription_pmi.detail')
      @registration_source_details_label = I18n.t('inscription_registration_source_details_label.pro')
      @child_min_birthdate = Date.today - 30.months
    when 2
      @terms_accepted_at_label = I18n.t('inscription_terms_accepted_at_label.parent')
      @registration_source_label = I18n.t('inscription_registration_source_label.parent')
      @registration_source_collection = :parent
      @registration_source_details_label = I18n.t('inscription_registration_source_details_label.parent')
      @child_min_birthdate = Child.min_birthdate
    else
      @terms_accepted_at_label = I18n.t('inscription_terms_accepted_at_label.parent')
      @registration_source_label = I18n.t('inscription_registration_source_label.parent')
      @registration_source_collection = :parent
      @registration_source_details_label = I18n.t('inscription_registration_source_details_label.parent')
      @child_min_birthdate = Child.min_birthdate_alt
    end
  end`

@registration_source_collection  est :parent quand c'est le formulaire 2 ou 1 qui est rempli (par un parent) et :pro quand c'est le formulaire 3 qui est rempli (par une pmi). Dans ce cas, on demande que le champs pmi_details soit rempli.

2021-11-08 13:32 UTC, levraipixel commented on app/views/children/new.html.erb
> +            <% if @registration_source_collection == :pro %>
ok ok

2021-11-08 13:32 UTC, levraipixel commented on app/models/child_support.rb
> +    validates "call#{call_idx}_status",
ah bien vu 👍🏻

2021-11-08 13:32 UTC, aristidebamenou commented on app/views/children/new.html.erb
> +            <% if @registration_source_collection == :pro %>
Je change le nom de la variable pour que ce soit plus clair?

2021-11-08 14:19 UTC, aristidebamenou commented on app/models/child_support.rb
> +    validates "call#{call_idx}_status",
J'aimerais transformer les "ko" et "ok" dans la base en "1_OK" ou "2_KO", je fais un rake ou une migration avec des requetes?

2021-11-09 08:41 UTC, levraipixel requested changes

2021-11-09 08:41 UTC, levraipixel commented on db/migrate/20211108155941_reformat_child_support_call_status.rb
> +        child_support.update_column "call#{call_idx}_status".to_sym, '1_ok'
`update_column` skip les validations (ce qui est OK pour moi) du coup autant utiliser directement `ChildSupport.where("unaccent(call#{call_idx}_status) ILIKE unaccent(?)", 'OK').update_all("call#{call_idx}_status" => '1_ok')`

2021-11-10 16:29 UTC, levraipixel approved these changes

2021-11-10 16:34 UTC, merged