feature: setup webhooks
milleetunmots/app pull request #315
Opened 2022-08-11 17:49 UTC by GRENOUILLETxavier

2022-08-12 08:59 UTC, karquelf requested changes
et ajouter des tests unitaires sur le service

2022-08-12 08:59 UTC, karquelf commented on app/controllers/children_controller.rb
> +      sms_url_form = "#{ENV['TYPEFORM_URL']}#support_id=#{@child.child_support.id}"
support_id => child_support_id

2022-08-12 08:59 UTC, karquelf commented on app/controllers/typeform_controller.rb
> +    service = Typeform::InitialForm.new(params[:form_response]).call
Typeform::InitialForm => Typeform::InitialFormService

2022-08-12 08:59 UTC, karquelf commented on app/models/child_support.rb
> +  READING_FREQUENCY = %w[none 1 2 3 4 5 6 7].freeze
Pas bon, il faut remettre comme avant et traduire les réponses du typeform de 0 à 7 vers [1_rarely 2_weekly 3_frequently 4_daily]

2022-08-12 08:59 UTC, karquelf commented on app/models/child_support.rb
> +  TV_FREQUENCY = %w[none 1 2 3 4 5 6 7].freeze
Faire la traduction comme Reading_Frequency vers [Tous les jours / + de 2 fois par semaine etc...] (Voir GDOC)

2022-08-12 08:59 UTC, karquelf commented on app/services/typeform/initial_form.rb
> +    attr_reader :errors, :data
:errors non nécéssaire car service utiliser dans un webhook
Il faut au contraire provoquer des erreurs 500 et avoir des exceptions dans rollbars/sentries si il y a une erreur car sinon personne ne sera au courant

2022-08-12 08:59 UTC, karquelf commented on app/services/typeform/initial_form.rb
> +      @errors = []
à retirer

2022-08-12 08:59 UTC, karquelf commented on app/services/typeform/initial_form.rb
> +            @data[:call1_reading_frequency] = answer[:choices][:labels].size
C'est ici qu'il faut traduire la réponse du typerform vers la fréquence voulu :
![image](https://user-images.githubusercontent.com/4288271/184320041-bd834817-90c4-445b-9b9c-4c0deb2a5555.png)

2022-08-12 08:59 UTC, karquelf commented on app/services/typeform/initial_form.rb
> +            @data[:call1_tv_frequency] = answer[:choices][:labels].size
pareil ici : 
![image](https://user-images.githubusercontent.com/4288271/184320120-d15d73db-2a5a-41c8-872d-20249c20a8c3.png)

2022-08-12 08:59 UTC, karquelf commented on app/services/typeform/initial_form.rb
> +      @errors << @parent2&.errors unless @parent2&.update(grade: @data[:other_parent_grade], grade_country: @data[:other_parent_grade_country])
@parent1.update!  pour émettre une exception si erreur
@parent2.update!

2022-08-12 08:59 UTC, karquelf commented on app/services/typeform/initial_form.rb
> +      unless @child_support.update(
update!

2022-08-12 08:59 UTC, karquelf commented on app/services/typeform/initial_form.rb
> +      @errors << @child_support.errors
pas d'erreurs

2022-08-12 08:59 UTC, karquelf commented on config/routes.rb
> +  post "/typeform", to: 'typeform#webhooks'
Utiliser la même structure que Spothit
=> post 'typeform/webhook'...

2022-08-12 10:17 UTC, GRENOUILLETxavier commented on app/services/typeform/initial_form.rb
> +            @data[:call1_tv_frequency] = answer[:choices][:labels].size
l'affichage c'est du front, donc ce serat dans la PR suivante, mais je mets les valeurs correspondante en back (ex: '1_rarely' plutot que '1')

2022-08-16 08:01 UTC, karquelf commented on app/helpers/application_helper.rb
> +  def digits_in_letter(digit)
n'est plus utilisé, je supprime

2022-08-16 08:12 UTC, karquelf approved these changes

2022-08-16 08:19 UTC, karquelf approved these changes

2022-08-16 08:27 UTC, karquelf requested changes

2022-08-16 08:27 UTC, karquelf commented on db/migrate/20220810111809_add_typeform_info_to_child_support.rb
> +    add_column :child_supports, :already_accompanied, :boolean
already_accompanied => already_working_with

2022-08-16 08:27 UTC, karquelf commented on db/migrate/20220810101423_add_grade_and_graded_in_france_to_parent.rb
> +    add_column :parents, :grade_country, :boolean
grade => degree

2022-08-16 09:06 UTC, karquelf approved these changes

2022-08-16 09:07 UTC, merged