Envoi de petites missions facilitées : suivi des messages envoyés
milleetunmots/app pull request #612
Opened 2023-09-14 14:06 UTC by aristidebamenou

https://trello.com/c/f5Dr7iM9

2023-09-19 14:37 UTC, alternatif requested changes

2023-09-19 14:37 UTC, alternatif commented on app/admin/message.rb
> +            option 'Appel 5', value: 'call3_goals'
Faut changer les values non ?

2023-09-19 14:37 UTC, alternatif commented on app/admin/message.rb
> +            option 'Appel 5', value: 'call3_goals'
Et faudrait demander s'il faut prévoir pour l'appel 6 ou non (si c'est pas déjà fait)

2023-09-20 05:59 UTC, aristidebamenou commented on app/admin/message.rb
> +            option 'Appel 5', value: 'call3_goals'
Oui il faut bien changer les valeurs. J'ai demandé à Mathieu, il m'a dit de s'arreter à l'appel 5

2023-09-20 07:42 UTC, alternatif approved these changes

2023-09-20 07:43 UTC, merged