fix : The scheduled jobs are no longer blocking
milleetunmots/app pull request #649
Opened 2023-10-24 08:26 UTC by aristidebamenou

2023-10-25 09:18 UTC, alternatif requested changes
Vérifier s'il n'y a pas d'autres automatisations où une fiche de suivi manquante serait bloquant.
S'il y en a : faire la même chose que pour le service de verify available module

2023-10-25 09:18 UTC, alternatif commented on app/jobs/children_support_module/verify_available_modules_task_job.rb
> +        next unless child.child_support
Enregistrer les cas repérés de la sorte : 
errors << "Ceci est une erreur" and next if child.child_support.blank?

2023-10-25 09:18 UTC, alternatif commented on app/jobs/children_support_module/verify_available_modules_task_job.rb
> +      return if child_support_link.blank?
Créer un rollbar et une tâche qui alertent sur le fait que certains enfants n'ont pas de fiche de suivi (s'il y en a), avant ce return

2023-10-27 08:57 UTC, alternatif requested changes

2023-10-27 08:57 UTC, alternatif commented on app/jobs/children_support_module/select_module_job.rb
> +                   group.children.where(group_status: 'active').joins(:child_support)
Cette ligne retournera uniquement les enfants associés à un child_support vu qu'on fait un joins. Donc soit on laisse comme avant pour détecter les éventuels enfants sans fiche de suivi, soit on peut retirer la gestion d'erreur concernant la fiche de suivi en dessous

2023-10-27 08:57 UTC, alternatif commented on app/services/child_support/fill_parents_available_support_modules_service.rb
> +    Rollbar.error(@errors) if @errors.any?
Envoyer un message explicite pour l'erreur et ajouter la liste des erreurs.
Exemple : `Rollbar.error("Certains enfants de la cohorte #{group_id} n'ont pas de fiche de suivi", children: @errors)`

2023-10-27 08:57 UTC, alternatif commented on app/services/child_support/fill_parents_available_support_modules_service.rb
> +        @errors["child: #{child.id}"] = "Cet enfant n'a pas de fiche de suivi"
Stocker uniquement les ID des enfants sans fiche de suivi si cette variable n'est utilisée que pour la détection des fiches de suivi manquantes

2023-10-27 08:57 UTC, alternatif commented on app/services/child_support/verify_available_modules_task_service.rb
> +    Rollbar.error(@errors) if @errors.any?
Pareil que plus haut

2023-10-27 08:57 UTC, alternatif commented on app/jobs/children_support_module/check_credits_for_group_job.rb
> +      Rollbar.error(check_service.errors.join("<br>"))
Passer un message explicite qui décrit l'erreur comme pour la Task, et un autre argument errors par exemple qui contiendra la liste des erreurs comme tu envoies ici actuellement.

2023-10-27 08:57 UTC, alternatif commented on app/jobs/children_support_module/select_default_support_module_job.rb
> +      Rollbar.error(errors) if errors.any?
Pareil que plus bas, envoyer un message explicite accompagné de la liste des erreurs rencontrées

2023-10-27 13:10 UTC, levraipixel commented on app/services/group/program_sms_to_bilinguals_service.rb
> +      return if @children.count.zero?
Tu peux probablement utiliser `size` ici au lieu de `count`, comme ça si c'est une collection et qu'elle a déjà été requêtée à la base, ça ne fait pas une seconde requête COUNT

2023-10-27 14:03 UTC, merged